services:
  - type: web
    name: agridrone-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    runtime: python
