services:
  - type: web
    name: corn-ai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # adjust for your actual entry point
    runtime: python
    build:
      env:
        PYTHON_VERSION: 3.11.9
