services:
  - type: web
    name: agri-drone-backend
    env: python
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    build:
      env:
        PYTHON_VERSION: 3.11.9
